// NOVAprint / Creative Commerce Studio: mesa de operaciones con sidebar persistente, datos jerarquizados y acentos de azul de tinta.
import { ArrowDownRight, ArrowUpRight, Bell, Box, CalendarDays, ChevronDown, Download, MoreHorizontal, PackageCheck, Plus, Search, Settings2, ShoppingBag, Sparkles, TrendingUp, Users } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";
import { AdminSidebar } from "@/components/AdminSidebar";
import { assetUrls, products, recentOrders } from "@/lib/nova-data";

const statCards = [
  { label: "Ventas totales", value: "18.420,50 €", change: "+12,8%", note: "vs. mes anterior", icon: TrendingUp, accent: "blue" },
  { label: "Pedidos", value: "248", change: "+8,4%", note: "este mes", icon: ShoppingBag, accent: "ink" },
  { label: "Pendientes", value: "8", change: "3 urgentes", note: "requieren atención", icon: PackageCheck, accent: "amber" },
  { label: "Clientes", value: "1.284", change: "+5,2%", note: "base activa", icon: Users, accent: "sky" },
];

const statusStyles: Record<string, string> = {
  Personalización: "bg-[#e8f0ff] text-[#2563eb]",
  Pagado: "bg-[#ecfdf3] text-[#19734a]",
  "En preparación": "bg-[#fff7e6] text-[#9a6700]",
  Enviado: "bg-[#f1f2ef] text-[#59636f]",
};

export default function AdminDashboard() {
  return (
    <div className="flex min-h-screen bg-[#f1f2ef] text-[#111111]">
      <AdminSidebar />
      <div className="min-w-0 flex-1">
        <header className="flex h-[76px] items-center justify-between border-b border-black/[.07] bg-[#f7f6f2] px-5 sm:px-8"><div className="pl-12 lg:pl-0"><div className="flex items-center gap-2 font-display text-[10px] font-bold uppercase tracking-[.14em] text-[#9ca3af]"><span>Workspace</span><span>/</span><span className="text-[#2563eb]">Dashboard</span></div><h1 className="mt-1 font-display text-xl font-semibold tracking-[-.04em]">Buenos días, Lucía.</h1></div><div className="flex items-center gap-2"><div className="hidden items-center gap-2 rounded-full border border-black/10 bg-white px-3 py-2 text-[11px] text-[#6b7280] md:flex"><Search size={14} /><span>Buscar en NOVAprint</span><kbd className="ml-4 rounded bg-[#f1f2ef] px-1.5 py-0.5 font-display text-[10px]">⌘ K</kbd></div><button type="button" aria-label="Notificaciones" className="grid h-10 w-10 place-items-center rounded-full border border-black/10 bg-white text-[#6b7280] hover:text-[#2563eb]"><Bell size={16} /></button><div className="hidden h-9 w-9 place-items-center rounded-full bg-[#2563eb] font-display text-[11px] font-bold text-white sm:grid">LM</div></div></header>
        <main className="nova-admin-bg nova-scrollbar max-h-[calc(100vh-76px)] overflow-y-auto px-5 py-7 sm:px-8 lg:px-10">
          <div className="mx-auto max-w-[1440px]">
            <section className="relative min-h-[192px] overflow-hidden rounded-[22px] bg-[#111111] p-6 text-white shadow-[0_18px_55px_rgba(17,17,17,.12)] sm:p-8"><img src="https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=1600&q=85" alt="Mesa de trabajo de diseño" className="absolute inset-0 h-full w-full object-cover object-center opacity-50" /><div className="absolute inset-0 bg-gradient-to-r from-[#111111] via-[#111111]/80 to-transparent" /><div className="relative max-w-[480px]"><div className="flex items-center gap-2 font-display text-[10px] font-bold uppercase tracking-[.16em] text-[#60a5fa]"><Sparkles size={14} /> Panel de control</div><h2 className="mt-4 font-display text-3xl font-semibold leading-[.98] tracking-[-.06em] sm:text-4xl">Tu tienda, una idea<br />más cerca de hacerse real.</h2><p className="mt-3 max-w-[330px] text-[12px] leading-5 text-white/55">Gestiona productos, diseños y pedidos desde el mismo lugar.</p></div><button type="button" onClick={() => toast.success("Selector de fecha preparado para conectar con datos reales.")} className="nova-press absolute bottom-6 right-6 hidden items-center gap-2 rounded-full bg-white/10 px-4 py-2.5 font-display text-[11px] font-bold text-white backdrop-blur-md transition-colors hover:bg-white/20 sm:flex"><CalendarDays size={14} /> Últimos 30 días <ChevronDown size={13} /></button></section>

            <section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{statCards.map((stat) => <div key={stat.label} className="nova-surface-flat nova-hover bg-white p-4"><div className="flex items-start justify-between"><div className={`grid h-9 w-9 place-items-center rounded-xl ${stat.accent === "blue" ? "bg-[#e8f0ff] text-[#2563eb]" : stat.accent === "sky" ? "bg-[#e0f2fe] text-[#0369a1]" : stat.accent === "amber" ? "bg-[#fff7e6] text-[#b7791f]" : "bg-[#f1f2ef] text-[#111111]"}`}><stat.icon size={16} /></div><MoreHorizontal size={17} className="text-[#c5cad0]" /></div><p className="mt-5 text-[11px] font-medium text-[#6b7280]">{stat.label}</p><div className="mt-1 flex items-end justify-between gap-3"><strong className="font-display text-2xl font-semibold tracking-[-.05em]">{stat.value}</strong><span className={`mb-1 inline-flex items-center gap-0.5 text-[10px] font-bold ${stat.change.startsWith("+") ? "text-[#19734a]" : "text-[#9a6700]"}`}>{stat.change.startsWith("+") ? <ArrowUpRight size={12} /> : <ArrowDownRight size={12} />}{stat.change}</span></div><p className="mt-1 text-[10px] text-[#9ca3af]">{stat.note}</p></div>)}</section>

            <section className="mt-5 grid gap-5 xl:grid-cols-[1.45fr_.85fr]">
              <div className="nova-surface-flat bg-white p-5 sm:p-6"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2"><span className="nova-kicker">Rendimiento</span><span className="rounded-full bg-[#ecfdf3] px-2 py-1 font-display text-[9px] font-bold text-[#19734a]">+12,8%</span></div><h2 className="mt-2 font-display text-2xl font-semibold tracking-[-.05em]">Ventas por día</h2></div><button type="button" onClick={() => toast.info("Descarga de informe disponible en la versión conectada.")} className="nova-press flex items-center gap-2 rounded-full border border-black/10 px-3 py-2 font-display text-[10px] font-bold text-[#6b7280] hover:border-[#2563eb] hover:text-[#2563eb]"><Download size={13} /> Exportar</button></div><div className="mt-8"><div className="flex h-[220px] items-end gap-2 border-b border-l border-black/10 px-3 pb-0 pt-4 sm:gap-3 sm:px-5"><div className="flex h-full flex-1 flex-col justify-between border-b-0 text-[9px] text-[#a5abb3]"><span>1.200 €</span><span>800 €</span><span>400 €</span><span>0 €</span></div><div className="relative h-full flex-[5]"><svg viewBox="0 0 620 190" preserveAspectRatio="none" className="h-full w-full overflow-visible"><defs><linearGradient id="novaArea" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#2563eb" stopOpacity=".22" /><stop offset="100%" stopColor="#2563eb" stopOpacity="0" /></linearGradient></defs><path d="M0,138 C28,145 40,116 68,123 S108,96 134,110 S165,70 196,94 S242,112 262,72 S298,58 320,74 S357,109 386,82 S421,65 449,80 S492,45 520,54 S566,23 620,40 L620,190 L0,190 Z" fill="url(#novaArea)" /><path d="M0,138 C28,145 40,116 68,123 S108,96 134,110 S165,70 196,94 S242,112 262,72 S298,58 320,74 S357,109 386,82 S421,65 449,80 S492,45 520,54 S566,23 620,40" fill="none" stroke="#2563eb" strokeWidth="3" strokeLinecap="round" /><circle cx="520" cy="54" r="5" fill="#fff" stroke="#2563eb" strokeWidth="3" /></svg><div className="absolute -bottom-7 left-0 right-0 flex justify-between font-display text-[9px] font-semibold text-[#9ca3af]"><span>01 jun</span><span>08 jun</span><span>15 jun</span><span>22 jun</span><span>30 jun</span></div></div></div></div><div className="mt-12 flex items-center justify-between border-t border-black/[.07] pt-4 text-[11px] text-[#6b7280]"><span>Ingresos acumulados</span><span className="font-display font-bold text-[#111111]">18.420,50 €</span></div></div>
              <div className="nova-surface-flat bg-white p-5 sm:p-6"><div className="flex items-start justify-between"><div><span className="nova-kicker">Catálogo</span><h2 className="mt-2 font-display text-2xl font-semibold tracking-[-.05em]">Más vendidos</h2></div><button type="button" className="text-[#9ca3af] hover:text-[#2563eb]"><MoreHorizontal size={18} /></button></div><div className="mt-7 space-y-5">{products.map((product, index) => <div key={product.id} className="flex items-center gap-3"><div className="relative h-12 w-12 shrink-0 overflow-hidden rounded-xl bg-[#e8f0ff]"><img src={product.image} alt="" className="h-full w-full object-cover" /><span className="absolute bottom-1 left-1 grid h-4 w-4 place-items-center rounded-full bg-white font-display text-[9px] font-bold text-[#2563eb]">0{index + 1}</span></div><div className="min-w-0 flex-1"><div className="truncate font-display text-[12px] font-semibold">{product.name}</div><div className="mt-1 text-[10px] text-[#9ca3af]">{product.stock} en stock · {product.category}</div></div><div className="text-right"><div className="font-display text-[12px] font-bold">{[86, 64, 42][index]} uds.</div><div className="mt-1 text-[10px] font-medium text-[#19734a]">+{[18, 12, 7][index]}%</div></div></div>)}</div><button type="button" onClick={() => toast.info("Catálogo completo disponible en la sección Productos.")} className="mt-8 flex w-full items-center justify-center gap-2 rounded-full border border-black/10 py-2.5 font-display text-[11px] font-bold text-[#374151] transition-colors hover:border-[#2563eb] hover:text-[#2563eb]">Ver catálogo <ArrowRightIcon /></button></div>
            </section>

            <section className="mt-5 nova-surface-flat overflow-hidden bg-white"><div className="flex flex-col gap-4 border-b border-black/[.07] p-5 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div><span className="nova-kicker">Actividad reciente</span><h2 className="mt-2 font-display text-2xl font-semibold tracking-[-.05em]">Últimos pedidos</h2></div><div className="flex gap-2"><button type="button" className="nova-press flex items-center gap-2 rounded-full border border-black/10 px-3 py-2 font-display text-[10px] font-bold text-[#6b7280] hover:border-[#2563eb] hover:text-[#2563eb]"><Download size={13} /> Exportar</button><button type="button" onClick={() => toast.success("Nuevo pedido manual listo para configurar.")} className="nova-press flex items-center gap-2 rounded-full bg-[#111111] px-3 py-2 font-display text-[10px] font-bold text-white hover:bg-[#2563eb]"><Plus size={13} /> Nuevo pedido</button></div></div><div className="nova-scrollbar overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-[#fafaf8] text-[10px] font-bold uppercase tracking-[.12em] text-[#9ca3af]"><tr><th className="px-6 py-3 font-semibold">Pedido</th><th className="px-4 py-3 font-semibold">Cliente</th><th className="px-4 py-3 font-semibold">Producto</th><th className="px-4 py-3 font-semibold">Estado</th><th className="px-4 py-3 font-semibold">Total</th><th className="px-6 py-3 text-right font-semibold">Fecha</th></tr></thead><tbody className="divide-y divide-black/[.06]">{recentOrders.map((order) => <tr key={order.id} className="text-[12px] transition-colors hover:bg-[#fafaf8]"><td className="px-6 py-4 font-display font-bold text-[#2563eb]">{order.id}</td><td className="px-4 py-4"><div className="font-semibold">{order.customer}</div><div className="mt-0.5 text-[10px] text-[#9ca3af]">Cliente recurrente</div></td><td className="px-4 py-4 text-[#6b7280]">{order.product}</td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${statusStyles[order.status] || "bg-[#f1f2ef] text-[#59636f]"}`}>{order.status}</span></td><td className="px-4 py-4 font-display font-bold">{order.total}</td><td className="px-6 py-4 text-right text-[#9ca3af]">{order.date}</td></tr>)}</tbody></table></div></section>

            <section className="mt-5 grid gap-5 pb-10 lg:grid-cols-[1fr_.7fr]">
              <div className="nova-surface-flat bg-[#111111] p-6 text-white"><div className="flex items-center justify-between"><div><span className="nova-kicker text-[#60a5fa]">Control de personalización</span><h2 className="mt-2 font-display text-2xl font-semibold tracking-[-.05em]">Todo listo para crear.</h2></div><div className="grid h-10 w-10 place-items-center rounded-full bg-[#2563eb]"><WandIcon /></div></div><div className="mt-7 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-white/[.07] p-3"><div className="font-display text-xl font-semibold">24</div><div className="mt-1 text-[10px] text-white/45">diseños activos</div></div><div className="rounded-xl bg-white/[.07] p-3"><div className="font-display text-xl font-semibold">6</div><div className="mt-1 text-[10px] text-white/45">tipografías</div></div><div className="rounded-xl bg-white/[.07] p-3"><div className="font-display text-xl font-semibold">18</div><div className="mt-1 text-[10px] text-white/45">reglas de precio</div></div></div><Link href="/personalizar" className="mt-6 inline-flex items-center gap-2 font-display text-[11px] font-bold text-[#60a5fa] no-underline hover:text-white">Probar configurador <ArrowUpRight size={14} /></Link></div>
              <div className="nova-surface-flat bg-white p-6"><div className="flex items-center justify-between"><div><span className="nova-kicker">Accesos rápidos</span><h2 className="mt-2 font-display text-2xl font-semibold tracking-[-.05em]">Ajusta tu tienda.</h2></div><Settings2 size={18} className="text-[#9ca3af]" /></div><div className="mt-6 space-y-2"><button type="button" onClick={() => toast.info("El editor de apariencia se abrirá en la versión completa.")} className="flex w-full items-center justify-between rounded-xl bg-[#f1f2ef] px-3 py-3 text-left text-[11px] font-semibold transition-colors hover:bg-[#e8f0ff] hover:text-[#2563eb]"><span>Editar apariencia</span><ArrowUpRight size={14} /></button><button type="button" onClick={() => toast.info("La biblioteca multimedia está preparada para conectar.")} className="flex w-full items-center justify-between rounded-xl bg-[#f1f2ef] px-3 py-3 text-left text-[11px] font-semibold transition-colors hover:bg-[#e8f0ff] hover:text-[#2563eb]"><span>Biblioteca multimedia</span><ArrowUpRight size={14} /></button><button type="button" onClick={() => toast.info("Reglas de precio editables en la sección Precios.")} className="flex w-full items-center justify-between rounded-xl bg-[#f1f2ef] px-3 py-3 text-left text-[11px] font-semibold transition-colors hover:bg-[#e8f0ff] hover:text-[#2563eb]"><span>Gestionar precios</span><ArrowUpRight size={14} /></button></div></div>
            </section>
          </div>
        </main>
      </div>
    </div>
  );
}

function ArrowRightIcon() { return <ArrowUpRight size={14} />; }
function WandIcon() { return <Sparkles size={17} />; }
