import { Link, useLocation } from "wouter";
import { ArrowLeft, CheckCircle2, CreditCard, ShoppingBag } from "lucide-react";
import { PublicHeader } from "@/components/PublicHeader";

export default function Cart() {
  const [, setLocation] = useLocation();
  const cancelled = new URLSearchParams(window.location.search).get("checkout") === "cancelled";
  return <div className="min-h-screen bg-[#f7f6f2] text-[#111111]"><PublicHeader /><main className="nova-container grid min-h-[calc(100vh-76px)] place-items-center py-16"><div className="w-full max-w-[520px] rounded-[28px] border border-black/[.07] bg-white p-8 text-center shadow-[0_18px_55px_rgba(17,17,17,.07)] sm:p-10">{cancelled ? <><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[#fff1e8] text-[#c26a2e"><CreditCard size={24} /></div><span className="nova-kicker mt-6 block">Checkout cancelado</span><h1 className="mt-3 font-display text-4xl font-semibold tracking-[-.07em]">Tu diseño sigue aquí.</h1><p className="mt-4 text-sm leading-6 text-[#6b7280]">No se ha cobrado nada. Puedes volver al configurador y continuar cuando quieras.</p></> : <><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[#e8f0ff] text-[#2563eb]"><ShoppingBag size={24} /></div><span className="nova-kicker mt-6 block">NOVAprint / Carrito</span><h1 className="mt-3 font-display text-4xl font-semibold tracking-[-.07em]">Tu carrito.</h1><p className="mt-4 text-sm leading-6 text-[#6b7280]">Elige un diseño para añadirlo al carrito y pasar al checkout seguro.</p></>}{cancelled && <div className="mt-6 flex items-center justify-center gap-2 text-[12px] font-semibold text-[#4f9f7a]"><CheckCircle2 size={15} /> Estado guardado en tu cuenta</div>}<div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/personalizar" className="nova-press inline-flex items-center justify-center gap-2 rounded-full bg-[#2563eb] px-5 py-3.5 font-display text-[12px] font-bold text-white no-underline hover:bg-[#1746a2]">Volver a diseñar</Link><button type="button" onClick={() => setLocation("/cuenta")} className="nova-press inline-flex items-center justify-center gap-2 rounded-full border border-black/10 px-5 py-3.5 font-display text-[12px] font-bold text-[#111111] hover:border-[#2563eb] hover:text-[#2563eb]"><ArrowLeft size={15} /> Mi cuenta</button></div></div></main></div>;
}
