// NOVAprint / Creative Commerce Studio: configurador en tres estaciones, con preview dominante y precio explicado en tiempo real.
import { ChangeEvent, useMemo, useRef, useState } from "react";
import { Link } from "wouter";
import { ArrowLeft, ArrowRight, ChevronDown, Eye, EyeOff, ImagePlus, Layers3, Minus, Plus, Redo2, RotateCw, ShoppingBag, Sparkles, Trash2, Type, Undo2, Upload, WandSparkles } from "lucide-react";
import { PublicHeader } from "@/components/PublicHeader";
import { AIDesignerModal, AIProposal } from "@/components/AIDesignerModal";
import { designs, priceRules, products } from "@/lib/nova-data";

const thermo = products[0];
const emojis = ["♥", "✦", "✳", "◒", "☼", "⌁"];

type Tool = "image" | "text" | "design";

export default function Configurator() {
  const fileRef = useRef<HTMLInputElement>(null);
  const [tool, setTool] = useState<Tool>("image");
  const [selectedColor, setSelectedColor] = useState(thermo.colors[0]);
  const [imageUrl, setImageUrl] = useState("");
  const [text, setText] = useState("");
  const [selectedDesign, setSelectedDesign] = useState<string | null>(null);
  const [selectedEmoji, setSelectedEmoji] = useState<string | null>(null);
  const [aiDesign, setAiDesign] = useState<AIProposal | null>(null);
  const [aiGenerated, setAiGenerated] = useState(false);
  const [aiOpen, setAiOpen] = useState(() => new URLSearchParams(window.location.search).get("ai") === "1");
  const [added, setAdded] = useState(false);
  const basePrice = thermo.price;
  const selectedDesignData = designs.find((design) => design.id === selectedDesign);
  const total = useMemo(() => basePrice + (imageUrl ? priceRules[0].value : 0) + (text.trim() ? priceRules[1].value : 0) + (selectedDesignData ? priceRules[2].value : 0) + (aiGenerated ? 2.99 : 0), [aiGenerated, imageUrl, selectedDesignData, text]);

  const handleImage = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => setImageUrl(String(reader.result));
    reader.readAsDataURL(file);
  };

  const thermoColorClass = selectedColor.name.toLowerCase().replace(" ", "-").replace("ó", "o");

  return (
    <div className="min-h-screen bg-[#f7f6f2] text-[#111111]">
      <PublicHeader />
      <main className="pb-16">
        <div className="nova-container pt-7"><Link href="/" className="inline-flex items-center gap-2 font-display text-[12px] font-semibold text-[#6b7280] no-underline transition-colors hover:text-[#2563eb]"><ArrowLeft size={15} /> Volver a NOVAprint</Link></div>
        <section className="nova-container mt-7 flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><span className="nova-kicker">Estudio / Producto 001</span><h1 className="mt-3 font-display text-4xl font-semibold tracking-[-.065em] sm:text-5xl">Diseña tu termo.</h1><p className="mt-3 text-sm leading-6 text-[#6b7280]">Empieza en blanco. Añade lo que te representa.</p></div><div className="flex flex-wrap items-center gap-2 md:justify-end"><button type="button" onClick={() => setAiOpen(true)} className="nova-press inline-flex items-center gap-2 rounded-full bg-[#111111] px-4 py-2.5 font-display text-[11px] font-bold text-white shadow-[0_8px_18px_rgba(17,17,17,.12)] transition-colors hover:bg-[#2563eb]"><Sparkles size={14} className="text-[#60a5fa]" /> Diseñar con IA</button><div className="hidden items-center gap-2 rounded-full border border-black/10 bg-white px-3 py-2 font-display text-[10px] font-bold uppercase tracking-[.12em] text-[#6b7280] sm:flex"><span className="h-2 w-2 rounded-full bg-[#2563eb]" /> Guardado automáticamente</div></div></section>

        <section className="nova-container mt-9 grid items-start gap-5 lg:grid-cols-[235px_minmax(0,1fr)_300px]">
          <aside className="order-2 space-y-3 lg:order-1">
            <div className="nova-surface-flat overflow-hidden bg-white"><div className="flex items-center justify-between border-b border-black/[.07] px-4 py-3"><span className="font-display text-[11px] font-bold uppercase tracking-[.12em]">Herramientas</span><WandSparkles size={15} className="text-[#2563eb]" /></div><div className="grid grid-cols-3 p-2">
              {([{ id: "image", label: "Imagen", icon: ImagePlus }, { id: "text", label: "Texto", icon: Type }, { id: "design", label: "Diseño", icon: Sparkles }] as const).map((item) => <button type="button" key={item.id} onClick={() => setTool(item.id)} className={`nova-press flex flex-col items-center gap-2 rounded-xl px-2 py-3 text-[10px] font-semibold transition-colors ${tool === item.id ? "bg-[#e8f0ff] text-[#2563eb]" : "text-[#6b7280] hover:bg-[#f1f2ef]"}`}><item.icon size={17} strokeWidth={1.8} />{item.label}</button>)}
            </div></div>
            <div className="nova-surface-flat bg-white p-4"><div className="flex items-center justify-between"><span className="font-display text-[11px] font-bold uppercase tracking-[.12em]">Color del termo</span><span className="text-[10px] text-[#9ca3af]">{selectedColor.name}</span></div><div className="mt-4 grid grid-cols-6 gap-2">{thermo.colors.map((color) => <button key={color.name} type="button" aria-label={`Color ${color.name}`} onClick={() => setSelectedColor(color)} className={`grid h-7 w-7 place-items-center rounded-full border-2 transition-transform hover:scale-110 ${selectedColor.name === color.name ? "border-[#2563eb]" : "border-transparent"}`}><span className="h-5 w-5 rounded-full border border-black/10" style={{ background: color.hex }} /></button>)}</div></div>
            <div className="nova-surface-flat bg-white p-4"><div className="flex items-center justify-between"><span className="font-display text-[11px] font-bold uppercase tracking-[.12em]">Acciones rápidas</span><span className="text-[10px] text-[#9ca3af]">⌘ Z</span></div><div className="mt-3 grid grid-cols-3 gap-2"><button type="button" aria-label="Deshacer" className="nova-press grid h-9 place-items-center rounded-lg bg-[#f1f2ef] text-[#6b7280] hover:bg-[#e8f0ff] hover:text-[#2563eb]"><Undo2 size={15} /></button><button type="button" aria-label="Rehacer" className="nova-press grid h-9 place-items-center rounded-lg bg-[#f1f2ef] text-[#6b7280] hover:bg-[#e8f0ff] hover:text-[#2563eb]"><Redo2 size={15} /></button><button type="button" aria-label="Restablecer" onClick={() => { setImageUrl(""); setText(""); setSelectedDesign(null); setSelectedEmoji(null); setAiDesign(null); setAiGenerated(false); }} className="nova-press grid h-9 place-items-center rounded-lg bg-[#f1f2ef] text-[#6b7280] hover:bg-[#fee2e2] hover:text-[#dc2626]"><RotateCw size={15} /></button></div></div>
          </aside>

          <div className="order-1 min-w-0 lg:order-2">
            <div className="nova-surface relative overflow-hidden bg-[#eceeea] p-3 sm:p-5"><div className="flex items-center justify-between pb-4"><div className="flex items-center gap-2 font-display text-[10px] font-bold uppercase tracking-[.14em] text-[#6b7280]"><span className="h-2 w-2 rounded-full bg-[#2563eb]" /> Área de impresión</div><div className="flex items-center gap-2 text-[10px] font-medium text-[#9ca3af]"><span>100%</span><ChevronDown size={13} /></div></div><div className="nova-product-canvas nova-grid-line flex min-h-[430px] items-center justify-center rounded-[18px] border border-black/[.05] sm:min-h-[540px]"><div className={`nova-thermo nova-thermo-${thermoColorClass}`}><div className="nova-thermo-label"><span style={{ color: aiDesign?.tone || selectedDesignData?.tone || "#2563eb" }}>{aiDesign?.mark || selectedDesignData?.mark || "N"}</span><span className={selectedColor.name === "Negro" ? "!text-white/75" : ""}>{aiDesign?.name || selectedDesignData?.name || "Diseña el tuyo"}</span></div>{imageUrl && <img src={imageUrl} alt="Tu imagen subida" className="absolute left-[26px] top-[126px] z-[3] h-[74px] w-[74px] rounded-xl object-cover opacity-90 shadow-lg" />}{text && <span className="absolute left-[26px] right-[26px] top-[212px] z-[3] text-center font-display text-[12px] font-bold text-[#111111]">{text}</span>}{selectedEmoji && <span className="absolute right-[22px] top-[196px] z-[3] rotate-[-12deg] text-xl">{selectedEmoji}</span>}</div><span className="absolute bottom-4 left-4 rounded-full bg-white/85 px-3 py-2 font-display text-[10px] font-semibold uppercase tracking-[.1em] text-[#6b7280] backdrop-blur-sm">Vista frontal · 01</span><span className="absolute bottom-4 right-4 hidden rounded-full border border-black/10 bg-white/80 px-3 py-2 font-display text-[10px] font-semibold text-[#6b7280] sm:block">Arrastra para mover</span></div></div>
            <div className="mt-3 flex items-center justify-between px-1"><div className="flex items-center gap-2 text-[11px] text-[#6b7280]"><span className="grid h-6 w-6 place-items-center rounded-full bg-[#e8f0ff] text-[#2563eb]"><Layers3 size={13} /></span>3 capas disponibles</div><div className="flex gap-1"><button type="button" className="nova-press grid h-8 w-8 place-items-center rounded-full border border-black/10 bg-white text-[#6b7280] hover:text-[#2563eb]"><Minus size={13} /></button><button type="button" className="nova-press grid h-8 w-8 place-items-center rounded-full border border-black/10 bg-white text-[#6b7280] hover:text-[#2563eb]"><Plus size={13} /></button></div></div>
          </div>

          <aside className="order-3 space-y-3 lg:sticky lg:top-[96px]">
            <div className="nova-surface-flat bg-white p-5"><div className="flex items-start justify-between gap-4"><div><span className="nova-kicker">Resumen</span><h2 className="mt-2 font-display text-xl font-semibold tracking-[-.04em]">Termo Nova 500ml</h2></div><span className="rounded-full bg-[#e8f0ff] px-2.5 py-1 font-display text-[10px] font-bold text-[#2563eb]">1 unidad</span></div><div className="mt-5 space-y-3 border-t border-black/[.08] pt-4 text-[12px]"> <div className="flex justify-between"><span className="text-[#6b7280]">Precio base</span><span className="font-semibold">{basePrice.toFixed(2).replace(".", ",")} €</span></div>{imageUrl && <div className="flex justify-between text-[#2563eb]"><span>Imagen personalizada</span><span>+3,00 €</span></div>}{text && <div className="flex justify-between text-[#2563eb]"><span>Texto personalizado</span><span>+1,50 €</span></div>}{selectedDesignData && <div className="flex justify-between text-[#2563eb]"><span>Diseño premium</span><span>+4,95 €</span></div>}{aiGenerated && <div className="flex justify-between text-[#2563eb]"><span>Pack AI Designer · 3 propuestas</span><span>+2,99 €</span></div>}</div><div className="mt-5 flex items-end justify-between border-t border-black/[.08] pt-4"><span className="font-display text-[11px] font-bold uppercase tracking-[.12em] text-[#6b7280]">Total</span><span className="font-display text-3xl font-semibold tracking-[-.06em]">{total.toFixed(2).replace(".", ",")} €</span></div><button type="button" onClick={() => setAdded(true)} className="nova-press mt-5 flex w-full items-center justify-center gap-2 rounded-full bg-[#2563eb] px-5 py-3.5 font-display text-[12px] font-bold text-white shadow-[0_12px_25px_rgba(37,99,235,.2)] transition-colors hover:bg-[#1746a2]"><ShoppingBag size={15} />{added ? "Añadido al carrito" : "Añadir al carrito"}</button>{added && <p className="mt-3 text-center text-[11px] font-medium text-[#2563eb]">Tu diseño está listo para continuar.</p>}</div>
            <div className="nova-surface-flat bg-white p-5"><div className="flex items-center justify-between"><span className="font-display text-[11px] font-bold uppercase tracking-[.12em]">Capas</span><span className="text-[10px] text-[#9ca3af]">{[imageUrl, text, selectedEmoji, selectedDesign].filter(Boolean).length || 1}/4</span></div><div className="mt-3 space-y-1.5">{[{ label: text || "Texto", active: Boolean(text), icon: Type }, { label: aiDesign?.name || selectedDesignData?.name || "Diseño", active: Boolean(selectedDesign || aiDesign), icon: Sparkles }, { label: imageUrl ? "Imagen subida" : "Foto", active: Boolean(imageUrl), icon: ImagePlus }].map((layer) => <div key={layer.label} className={`flex items-center gap-2.5 rounded-lg px-2.5 py-2 text-[11px] ${layer.active ? "bg-[#e8f0ff] text-[#1746a2]" : "text-[#9ca3af]"}`}><layer.icon size={14} /><span className="flex-1 truncate">{layer.label}</span>{layer.active ? <Eye size={14} /> : <EyeOff size={14} />}<button type="button" aria-label={`Eliminar ${layer.label}`} className="ml-1 opacity-50 hover:text-[#dc2626] hover:opacity-100"><Trash2 size={13} /></button></div>)}</div></div>
          </aside>
        </section>

        <section className="nova-container mt-8 grid gap-5 lg:grid-cols-[1fr_1fr]">
          <div className="nova-surface-flat bg-white p-5"><div className="flex items-center justify-between"><div><span className="nova-kicker">Añade algo tuyo</span><h2 className="mt-2 font-display text-xl font-semibold tracking-[-.04em]">Tu imagen o tu frase.</h2></div><span className="rounded-full bg-[#f1f2ef] px-2.5 py-1 text-[10px] font-semibold text-[#6b7280]">Paso 02</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><button type="button" onClick={() => fileRef.current?.click()} className="nova-press flex min-h-[126px] flex-col items-center justify-center gap-2 rounded-2xl border border-dashed border-[#9ab8ef] bg-[#f6f9ff] text-center transition-colors hover:border-[#2563eb] hover:bg-[#e8f0ff]"><Upload size={20} className="text-[#2563eb]" /><span className="font-display text-[12px] font-bold">Subir mi imagen</span><span className="text-[10px] text-[#6b7280]">JPG, PNG, WEBP · Máx. 10 MB</span></button><div className="rounded-2xl border border-black/[.07] bg-[#fafaf8] p-4"><label htmlFor="nova-text" className="font-display text-[11px] font-bold uppercase tracking-[.1em] text-[#6b7280]">Añadir texto</label><input id="nova-text" value={text} onChange={(event) => setText(event.target.value)} placeholder="Escribe algo..." className="mt-4 w-full border-0 border-b border-black/15 bg-transparent pb-2 font-display text-lg font-semibold outline-none placeholder:text-[#c2c7cc] focus:border-[#2563eb]" /><div className="mt-3 flex gap-1.5">{emojis.map((emoji) => <button type="button" key={emoji} onClick={() => setSelectedEmoji(selectedEmoji === emoji ? null : emoji)} className={`grid h-7 w-7 place-items-center rounded-full text-sm ${selectedEmoji === emoji ? "bg-[#e8f0ff]" : "bg-[#f1f2ef] hover:bg-[#e8f0ff]"}`}>{emoji}</button>)}</div></div></div><input ref={fileRef} type="file" accept=".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp" onChange={handleImage} className="hidden" /></div>
          <div className="nova-surface-flat bg-white p-5"><div className="flex items-start justify-between"><div><span className="nova-kicker">Punto de partida</span><h2 className="mt-2 font-display text-xl font-semibold tracking-[-.04em]">También puedes empezar con un diseño.</h2></div><span className="rounded-full bg-[#e8f0ff] px-2.5 py-1 text-[10px] font-semibold text-[#2563eb]">+4,95 €</span></div><div className="mt-5 grid grid-cols-3 gap-2 sm:grid-cols-6">{designs.map((design) => <button type="button" key={design.id} onClick={() => { setSelectedDesign(selectedDesign === design.id ? null : design.id); setAiDesign(null); setAiGenerated(false); }} className={`nova-press group rounded-xl border p-2 text-center transition-all ${selectedDesign === design.id ? "border-[#2563eb] bg-[#e8f0ff]" : "border-black/[.07] hover:border-[#9ab8ef]"}`}><span className="mx-auto grid h-11 w-11 place-items-center rounded-lg font-display text-xl" style={{ background: `${design.tone}18`, color: design.tone }}>{design.mark}</span><span className="mt-2 block truncate text-[10px] font-semibold text-[#6b7280]">{design.name}</span></button>)}</div></div>
        </section>
        <div className="nova-container mt-6 flex items-center justify-between border-t border-black/[.08] pt-5 text-[11px] text-[#6b7280]"><span>Los precios proceden de la configuración de NOVAprint.</span><Link href="/admin" className="inline-flex items-center gap-1 font-semibold text-[#2563eb] no-underline hover:text-[#1746a2]">Ver cómo se gestiona <ArrowRight size={13} /></Link></div>
      </main>
      <AIDesignerModal open={aiOpen} onClose={() => setAiOpen(false)} onUseDesign={(proposal) => { setAiDesign(proposal); setSelectedDesign(null); setAiGenerated(true); setTool("design"); }} />
    </div>
  );
}
